volumes:
  postgres:
  media:

services:
  postgres:
    # this obscure image is chosen because it has x86_64 and arm64 support
    image: duvel/postgis:15-3.3
    restart: unless-stopped
    stop_grace_period: 0s
    healthcheck:
      interval: 5s
      timeout: 4s
      start_period: 10s
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
    volumes:
      - postgres:/home/postgres/pgdata/data
    environment:
      - "POSTGRES_DB=fred"
      - "POSTGRES_PASSWORD=NoCI!11"
    ports:
      - 5432:5432/tcp

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: migrate/migrate:v4.17.1
    restart: no
    stop_grace_period: 0s
    volumes:
      - ./database/migrations:/migrations
    command: >
      --source file:///migrations
      --database postgres://postgres:NoCI!11@postgres:5432/fred?sslmode=disable
      up

  post-migrate:
    depends_on:
      migrate:
        condition: service_completed_successfully
    # this obscure image is chosen because it has x86_64 and arm64 support
    image: duvel/postgis:15-3.3
    restart: no
    stop_grace_period: 0s
    entrypoint: ["/bin/bash", "-c"]
    command: "PAGER=cat PGPASSWORD=NoCI!11 psql -h postgres -p 5432 -U postgres -a fred -c 'VACUUM FULL; VACUUM ANALYZE;'"

  redis:
    image: redis:7.2.5
    restart: unless-stopped
    stop_grace_period: 0s
    ports:
      - 6379:6379/tcp

  swagger:
    restart: unless-stopped
    stop_grace_period: 0s
    image: swaggerapi/swagger-ui:v5.4.2
    environment:
      - "BASE_URL=/"
      - "SWAGGER_JSON_URL=http://host.docker.internal:7070/api/openapi.json"
    ports:
      - "7071:8080/tcp"
