objects:
  - name: repository
    properties:
      - url text NOT NULL
      - name text NULL
      - handled_at timestamptz NOT NULL DEFAULT to_timestamp(0)
    claims:
      - repository_syncer

  - name: change
    properties:
      - commit_hash text NOT NULL
      - branch text NOT NULL
      - tag text NULL
      - message text NOT NULL
      - authored_by text NOT NULL
      - authored_at timestamptz NOT NULL
      - committed_by text NOT NULL
      - committed_at timestamptz NOT NULL
      - handled_at timestamptz NULL
    unique_on:
      - ["commit_hash", "repository_id"]
    claims:
      - job_coordinator

  - name: job
    properties:
      - name text NOT NULL
      - branches text NULL
      - tags text NULL
    unique_on:
      - ["name"]

  - name: depends_on

  - name: execution
    properties:
      - status text NOT NULL CHECK (status IN ('pending', 'running', 'succeeded', 'failing', 'failed', 'erroring', 'errored', 'skipped'))
      - started_at timestamptz NULL DEFAULT NULL
      - ended_at timestamptz NULL DEFAULT NULL CHECK (ended_at IS null OR ended_at >= started_at)
    claims:
      - job_executor

  - name: task
    properties:
      - name TEXT NOT NULL CHECK (name ~* '^[A-Za-z0-9-]+$')
      - index integer NOT NULL
      - platform text NOT NULL CHECK (platform ~* '^.*/.*$')
      - image text NOT NULL CHECK (image ~* '^(?:(?=[^:\/]{1,253})(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(?:\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*(?::[0-9]{1,5})?/)?((?![._-])(?:[a-z0-9._-]*)(?<![._-])(?:/(?![._-])[a-z0-9._-]*(?<![._-]))*)(?::(?![.-])[a-zA-Z0-9_.-]{1,128})?$')
      - script text NOT NULL
    unique_on:
      - ["name", "job_id"]

  - name: output
    properties:
      - status text NOT NULL CHECK (status IN ('pending', 'running', 'succeeded', 'failing', 'failed', 'erroring', 'errored', 'skipped'))
      - started_at timestamptz NULL DEFAULT NULL
      - ended_at timestamptz NULL DEFAULT NULL
      - exit_status int NOT NULL
      - error text NULL

  - name: log
    properties:
      - buffer bytea NOT NULL

relationships:
  - source: repository
    destination: change
    type: one-to-many

  - source: repository
    destination: job
    type: one-to-many

  - source: change
    destination: execution
    type: one-to-many

  - source: job
    destination: execution
    type: one-to-many

  - source: job
    destination: task
    type: one-to-many

  - source: job
    destination: depends_on
    type: one-to-many
    name: source

  - source: job
    destination: depends_on
    type: one-to-many
    name: sink

  - source: execution
    destination: output
    type: one-to-many

  - source: task
    destination: output
    type: one-to-many

  - source: output
    destination: log
    type: one-to-one
