
DROP TABLE IF EXISTS public.repository CASCADE;
DROP TABLE IF EXISTS public.rule CASCADE;
DROP TABLE IF EXISTS public.job CASCADE;
DROP TABLE IF EXISTS public.task CASCADE;
DROP TABLE IF EXISTS public.change CASCADE;
DROP TABLE IF EXISTS public.execution CASCADE;
DROP TABLE IF EXISTS public.output CASCADE;
DROP TABLE IF EXISTS public.log CASCADE;
DROP TABLE IF EXISTS public.m2m_rule_trigger_job CASCADE;
