/*
Djangolang

Testing ChangeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api_client

import (
	"context"
	"testing"

	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_api_client_ChangeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChangeAPIService DeleteChange", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var primaryKey string

		httpRes, err := apiClient.ChangeAPI.DeleteChange(context.Background(), primaryKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChangeAPIService GetChange", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var primaryKey string

		resp, httpRes, err := apiClient.ChangeAPI.GetChange(context.Background(), primaryKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChangeAPIService GetChanges", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ChangeAPI.GetChanges(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChangeAPIService PatchChange", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var primaryKey string

		resp, httpRes, err := apiClient.ChangeAPI.PatchChange(context.Background(), primaryKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChangeAPIService PostChanges", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ChangeAPI.PostChanges(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
