/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the Execution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Execution{}

// Execution struct for Execution
type Execution struct {
	ChangeId                             *string    `json:"change_id,omitempty"`
	ChangeIdObject                       *Change    `json:"change_id_object,omitempty"`
	CreatedAt                            *time.Time `json:"created_at,omitempty"`
	DeletedAt                            *time.Time `json:"deleted_at,omitempty"`
	EndedAt                              *time.Time `json:"ended_at,omitempty"`
	Id                                   *string    `json:"id,omitempty"`
	JobExecutorClaimedUntil              *time.Time `json:"job_executor_claimed_until,omitempty"`
	JobId                                *string    `json:"job_id,omitempty"`
	JobIdObject                          *Job       `json:"job_id_object,omitempty"`
	ReferencedByOutputExecutionIdObjects []Output   `json:"referenced_by_output_execution_id_objects,omitempty"`
	StartedAt                            *time.Time `json:"started_at,omitempty"`
	Status                               *string    `json:"status,omitempty"`
	TriggerId                            *string    `json:"trigger_id,omitempty"`
	TriggerIdObject                      *Trigger   `json:"trigger_id_object,omitempty"`
	UpdatedAt                            *time.Time `json:"updated_at,omitempty"`
}

// NewExecution instantiates a new Execution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecution() *Execution {
	this := Execution{}
	return &this
}

// NewExecutionWithDefaults instantiates a new Execution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionWithDefaults() *Execution {
	this := Execution{}
	return &this
}

// GetChangeId returns the ChangeId field value if set, zero value otherwise.
func (o *Execution) GetChangeId() string {
	if o == nil || IsNil(o.ChangeId) {
		var ret string
		return ret
	}
	return *o.ChangeId
}

// GetChangeIdOk returns a tuple with the ChangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetChangeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeId) {
		return nil, false
	}
	return o.ChangeId, true
}

// HasChangeId returns a boolean if a field has been set.
func (o *Execution) HasChangeId() bool {
	if o != nil && !IsNil(o.ChangeId) {
		return true
	}

	return false
}

// SetChangeId gets a reference to the given string and assigns it to the ChangeId field.
func (o *Execution) SetChangeId(v string) {
	o.ChangeId = &v
}

// GetChangeIdObject returns the ChangeIdObject field value if set, zero value otherwise.
func (o *Execution) GetChangeIdObject() Change {
	if o == nil || IsNil(o.ChangeIdObject) {
		var ret Change
		return ret
	}
	return *o.ChangeIdObject
}

// GetChangeIdObjectOk returns a tuple with the ChangeIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetChangeIdObjectOk() (*Change, bool) {
	if o == nil || IsNil(o.ChangeIdObject) {
		return nil, false
	}
	return o.ChangeIdObject, true
}

// HasChangeIdObject returns a boolean if a field has been set.
func (o *Execution) HasChangeIdObject() bool {
	if o != nil && !IsNil(o.ChangeIdObject) {
		return true
	}

	return false
}

// SetChangeIdObject gets a reference to the given Change and assigns it to the ChangeIdObject field.
func (o *Execution) SetChangeIdObject(v Change) {
	o.ChangeIdObject = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Execution) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Execution) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Execution) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Execution) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Execution) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *Execution) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *Execution) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *Execution) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *Execution) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Execution) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Execution) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Execution) SetId(v string) {
	o.Id = &v
}

// GetJobExecutorClaimedUntil returns the JobExecutorClaimedUntil field value if set, zero value otherwise.
func (o *Execution) GetJobExecutorClaimedUntil() time.Time {
	if o == nil || IsNil(o.JobExecutorClaimedUntil) {
		var ret time.Time
		return ret
	}
	return *o.JobExecutorClaimedUntil
}

// GetJobExecutorClaimedUntilOk returns a tuple with the JobExecutorClaimedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetJobExecutorClaimedUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.JobExecutorClaimedUntil) {
		return nil, false
	}
	return o.JobExecutorClaimedUntil, true
}

// HasJobExecutorClaimedUntil returns a boolean if a field has been set.
func (o *Execution) HasJobExecutorClaimedUntil() bool {
	if o != nil && !IsNil(o.JobExecutorClaimedUntil) {
		return true
	}

	return false
}

// SetJobExecutorClaimedUntil gets a reference to the given time.Time and assigns it to the JobExecutorClaimedUntil field.
func (o *Execution) SetJobExecutorClaimedUntil(v time.Time) {
	o.JobExecutorClaimedUntil = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *Execution) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *Execution) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *Execution) SetJobId(v string) {
	o.JobId = &v
}

// GetJobIdObject returns the JobIdObject field value if set, zero value otherwise.
func (o *Execution) GetJobIdObject() Job {
	if o == nil || IsNil(o.JobIdObject) {
		var ret Job
		return ret
	}
	return *o.JobIdObject
}

// GetJobIdObjectOk returns a tuple with the JobIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetJobIdObjectOk() (*Job, bool) {
	if o == nil || IsNil(o.JobIdObject) {
		return nil, false
	}
	return o.JobIdObject, true
}

// HasJobIdObject returns a boolean if a field has been set.
func (o *Execution) HasJobIdObject() bool {
	if o != nil && !IsNil(o.JobIdObject) {
		return true
	}

	return false
}

// SetJobIdObject gets a reference to the given Job and assigns it to the JobIdObject field.
func (o *Execution) SetJobIdObject(v Job) {
	o.JobIdObject = &v
}

// GetReferencedByOutputExecutionIdObjects returns the ReferencedByOutputExecutionIdObjects field value if set, zero value otherwise.
func (o *Execution) GetReferencedByOutputExecutionIdObjects() []Output {
	if o == nil || IsNil(o.ReferencedByOutputExecutionIdObjects) {
		var ret []Output
		return ret
	}
	return o.ReferencedByOutputExecutionIdObjects
}

// GetReferencedByOutputExecutionIdObjectsOk returns a tuple with the ReferencedByOutputExecutionIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetReferencedByOutputExecutionIdObjectsOk() ([]Output, bool) {
	if o == nil || IsNil(o.ReferencedByOutputExecutionIdObjects) {
		return nil, false
	}
	return o.ReferencedByOutputExecutionIdObjects, true
}

// HasReferencedByOutputExecutionIdObjects returns a boolean if a field has been set.
func (o *Execution) HasReferencedByOutputExecutionIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByOutputExecutionIdObjects) {
		return true
	}

	return false
}

// SetReferencedByOutputExecutionIdObjects gets a reference to the given []Output and assigns it to the ReferencedByOutputExecutionIdObjects field.
func (o *Execution) SetReferencedByOutputExecutionIdObjects(v []Output) {
	o.ReferencedByOutputExecutionIdObjects = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *Execution) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *Execution) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *Execution) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Execution) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Execution) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Execution) SetStatus(v string) {
	o.Status = &v
}

// GetTriggerId returns the TriggerId field value if set, zero value otherwise.
func (o *Execution) GetTriggerId() string {
	if o == nil || IsNil(o.TriggerId) {
		var ret string
		return ret
	}
	return *o.TriggerId
}

// GetTriggerIdOk returns a tuple with the TriggerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetTriggerIdOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerId) {
		return nil, false
	}
	return o.TriggerId, true
}

// HasTriggerId returns a boolean if a field has been set.
func (o *Execution) HasTriggerId() bool {
	if o != nil && !IsNil(o.TriggerId) {
		return true
	}

	return false
}

// SetTriggerId gets a reference to the given string and assigns it to the TriggerId field.
func (o *Execution) SetTriggerId(v string) {
	o.TriggerId = &v
}

// GetTriggerIdObject returns the TriggerIdObject field value if set, zero value otherwise.
func (o *Execution) GetTriggerIdObject() Trigger {
	if o == nil || IsNil(o.TriggerIdObject) {
		var ret Trigger
		return ret
	}
	return *o.TriggerIdObject
}

// GetTriggerIdObjectOk returns a tuple with the TriggerIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetTriggerIdObjectOk() (*Trigger, bool) {
	if o == nil || IsNil(o.TriggerIdObject) {
		return nil, false
	}
	return o.TriggerIdObject, true
}

// HasTriggerIdObject returns a boolean if a field has been set.
func (o *Execution) HasTriggerIdObject() bool {
	if o != nil && !IsNil(o.TriggerIdObject) {
		return true
	}

	return false
}

// SetTriggerIdObject gets a reference to the given Trigger and assigns it to the TriggerIdObject field.
func (o *Execution) SetTriggerIdObject(v Trigger) {
	o.TriggerIdObject = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Execution) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Execution) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Execution) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Execution) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Execution) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Execution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChangeId) {
		toSerialize["change_id"] = o.ChangeId
	}
	if !IsNil(o.ChangeIdObject) {
		toSerialize["change_id_object"] = o.ChangeIdObject
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.EndedAt) {
		toSerialize["ended_at"] = o.EndedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JobExecutorClaimedUntil) {
		toSerialize["job_executor_claimed_until"] = o.JobExecutorClaimedUntil
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.JobIdObject) {
		toSerialize["job_id_object"] = o.JobIdObject
	}
	if !IsNil(o.ReferencedByOutputExecutionIdObjects) {
		toSerialize["referenced_by_output_execution_id_objects"] = o.ReferencedByOutputExecutionIdObjects
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TriggerId) {
		toSerialize["trigger_id"] = o.TriggerId
	}
	if !IsNil(o.TriggerIdObject) {
		toSerialize["trigger_id_object"] = o.TriggerIdObject
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableExecution struct {
	value *Execution
	isSet bool
}

func (v NullableExecution) Get() *Execution {
	return v.value
}

func (v *NullableExecution) Set(val *Execution) {
	v.value = val
	v.isSet = true
}

func (v NullableExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecution(val *Execution) *NullableExecution {
	return &NullableExecution{value: val, isSet: true}
}

func (v NullableExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
