/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the Job type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Job{}

// Job struct for Job
type Job struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ReferencedByRuleJobTriggerJobIdObjects []Rule `json:"referenced_by_rule_job_trigger_job_id_objects,omitempty"`
	ReferencedByTaskJobIdObjects []Rule `json:"referenced_by_task_job_id_objects,omitempty"`
	RuleTriggerRuleId *string `json:"rule_trigger_rule_id,omitempty"`
	RuleTriggerRuleIdObject *Rule `json:"rule_trigger_rule_id_object,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewJob instantiates a new Job object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJob() *Job {
	this := Job{}
	return &this
}

// NewJobWithDefaults instantiates a new Job object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobWithDefaults() *Job {
	this := Job{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Job) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Job) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Job) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Job) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Job) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *Job) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Job) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Job) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Job) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Job) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Job) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Job) SetName(v string) {
	o.Name = &v
}

// GetReferencedByRuleJobTriggerJobIdObjects returns the ReferencedByRuleJobTriggerJobIdObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetReferencedByRuleJobTriggerJobIdObjects() []Rule {
	if o == nil {
		var ret []Rule
		return ret
	}
	return o.ReferencedByRuleJobTriggerJobIdObjects
}

// GetReferencedByRuleJobTriggerJobIdObjectsOk returns a tuple with the ReferencedByRuleJobTriggerJobIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetReferencedByRuleJobTriggerJobIdObjectsOk() ([]Rule, bool) {
	if o == nil || IsNil(o.ReferencedByRuleJobTriggerJobIdObjects) {
		return nil, false
	}
	return o.ReferencedByRuleJobTriggerJobIdObjects, true
}

// HasReferencedByRuleJobTriggerJobIdObjects returns a boolean if a field has been set.
func (o *Job) HasReferencedByRuleJobTriggerJobIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByRuleJobTriggerJobIdObjects) {
		return true
	}

	return false
}

// SetReferencedByRuleJobTriggerJobIdObjects gets a reference to the given []Rule and assigns it to the ReferencedByRuleJobTriggerJobIdObjects field.
func (o *Job) SetReferencedByRuleJobTriggerJobIdObjects(v []Rule) {
	o.ReferencedByRuleJobTriggerJobIdObjects = v
}

// GetReferencedByTaskJobIdObjects returns the ReferencedByTaskJobIdObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetReferencedByTaskJobIdObjects() []Rule {
	if o == nil {
		var ret []Rule
		return ret
	}
	return o.ReferencedByTaskJobIdObjects
}

// GetReferencedByTaskJobIdObjectsOk returns a tuple with the ReferencedByTaskJobIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetReferencedByTaskJobIdObjectsOk() ([]Rule, bool) {
	if o == nil || IsNil(o.ReferencedByTaskJobIdObjects) {
		return nil, false
	}
	return o.ReferencedByTaskJobIdObjects, true
}

// HasReferencedByTaskJobIdObjects returns a boolean if a field has been set.
func (o *Job) HasReferencedByTaskJobIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByTaskJobIdObjects) {
		return true
	}

	return false
}

// SetReferencedByTaskJobIdObjects gets a reference to the given []Rule and assigns it to the ReferencedByTaskJobIdObjects field.
func (o *Job) SetReferencedByTaskJobIdObjects(v []Rule) {
	o.ReferencedByTaskJobIdObjects = v
}

// GetRuleTriggerRuleId returns the RuleTriggerRuleId field value if set, zero value otherwise.
func (o *Job) GetRuleTriggerRuleId() string {
	if o == nil || IsNil(o.RuleTriggerRuleId) {
		var ret string
		return ret
	}
	return *o.RuleTriggerRuleId
}

// GetRuleTriggerRuleIdOk returns a tuple with the RuleTriggerRuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetRuleTriggerRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleTriggerRuleId) {
		return nil, false
	}
	return o.RuleTriggerRuleId, true
}

// HasRuleTriggerRuleId returns a boolean if a field has been set.
func (o *Job) HasRuleTriggerRuleId() bool {
	if o != nil && !IsNil(o.RuleTriggerRuleId) {
		return true
	}

	return false
}

// SetRuleTriggerRuleId gets a reference to the given string and assigns it to the RuleTriggerRuleId field.
func (o *Job) SetRuleTriggerRuleId(v string) {
	o.RuleTriggerRuleId = &v
}

// GetRuleTriggerRuleIdObject returns the RuleTriggerRuleIdObject field value if set, zero value otherwise.
func (o *Job) GetRuleTriggerRuleIdObject() Rule {
	if o == nil || IsNil(o.RuleTriggerRuleIdObject) {
		var ret Rule
		return ret
	}
	return *o.RuleTriggerRuleIdObject
}

// GetRuleTriggerRuleIdObjectOk returns a tuple with the RuleTriggerRuleIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetRuleTriggerRuleIdObjectOk() (*Rule, bool) {
	if o == nil || IsNil(o.RuleTriggerRuleIdObject) {
		return nil, false
	}
	return o.RuleTriggerRuleIdObject, true
}

// HasRuleTriggerRuleIdObject returns a boolean if a field has been set.
func (o *Job) HasRuleTriggerRuleIdObject() bool {
	if o != nil && !IsNil(o.RuleTriggerRuleIdObject) {
		return true
	}

	return false
}

// SetRuleTriggerRuleIdObject gets a reference to the given Rule and assigns it to the RuleTriggerRuleIdObject field.
func (o *Job) SetRuleTriggerRuleIdObject(v Rule) {
	o.RuleTriggerRuleIdObject = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Job) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Job) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Job) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Job) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Job) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.ReferencedByRuleJobTriggerJobIdObjects != nil {
		toSerialize["referenced_by_rule_job_trigger_job_id_objects"] = o.ReferencedByRuleJobTriggerJobIdObjects
	}
	if o.ReferencedByTaskJobIdObjects != nil {
		toSerialize["referenced_by_task_job_id_objects"] = o.ReferencedByTaskJobIdObjects
	}
	if !IsNil(o.RuleTriggerRuleId) {
		toSerialize["rule_trigger_rule_id"] = o.RuleTriggerRuleId
	}
	if !IsNil(o.RuleTriggerRuleIdObject) {
		toSerialize["rule_trigger_rule_id_object"] = o.RuleTriggerRuleIdObject
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableJob struct {
	value *Job
	isSet bool
}

func (v NullableJob) Get() *Job {
	return v.value
}

func (v *NullableJob) Set(val *Job) {
	v.value = val
	v.isSet = true
}

func (v NullableJob) IsSet() bool {
	return v.isSet
}

func (v *NullableJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJob(val *Job) *NullableJob {
	return &NullableJob{value: val, isSet: true}
}

func (v NullableJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


