/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the Repository type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Repository{}

// Repository struct for Repository
type Repository struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	HandledAt *time.Time `json:"handled_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ReferencedByChangeRepositoryIdObjects []Change `json:"referenced_by_change_repository_id_objects,omitempty"`
	ReferencedByJobRepositoryIdObjects []Job `json:"referenced_by_job_repository_id_objects,omitempty"`
	RepositorySyncerClaimedUntil *time.Time `json:"repository_syncer_claimed_until,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewRepository instantiates a new Repository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepository() *Repository {
	this := Repository{}
	return &this
}

// NewRepositoryWithDefaults instantiates a new Repository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryWithDefaults() *Repository {
	this := Repository{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Repository) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Repository) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Repository) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *Repository) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Repository) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *Repository) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetHandledAt returns the HandledAt field value if set, zero value otherwise.
func (o *Repository) GetHandledAt() time.Time {
	if o == nil || IsNil(o.HandledAt) {
		var ret time.Time
		return ret
	}
	return *o.HandledAt
}

// GetHandledAtOk returns a tuple with the HandledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetHandledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.HandledAt) {
		return nil, false
	}
	return o.HandledAt, true
}

// HasHandledAt returns a boolean if a field has been set.
func (o *Repository) HasHandledAt() bool {
	if o != nil && !IsNil(o.HandledAt) {
		return true
	}

	return false
}

// SetHandledAt gets a reference to the given time.Time and assigns it to the HandledAt field.
func (o *Repository) SetHandledAt(v time.Time) {
	o.HandledAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Repository) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Repository) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Repository) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Repository) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Repository) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Repository) SetName(v string) {
	o.Name = &v
}

// GetReferencedByChangeRepositoryIdObjects returns the ReferencedByChangeRepositoryIdObjects field value if set, zero value otherwise.
func (o *Repository) GetReferencedByChangeRepositoryIdObjects() []Change {
	if o == nil || IsNil(o.ReferencedByChangeRepositoryIdObjects) {
		var ret []Change
		return ret
	}
	return o.ReferencedByChangeRepositoryIdObjects
}

// GetReferencedByChangeRepositoryIdObjectsOk returns a tuple with the ReferencedByChangeRepositoryIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetReferencedByChangeRepositoryIdObjectsOk() ([]Change, bool) {
	if o == nil || IsNil(o.ReferencedByChangeRepositoryIdObjects) {
		return nil, false
	}
	return o.ReferencedByChangeRepositoryIdObjects, true
}

// HasReferencedByChangeRepositoryIdObjects returns a boolean if a field has been set.
func (o *Repository) HasReferencedByChangeRepositoryIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByChangeRepositoryIdObjects) {
		return true
	}

	return false
}

// SetReferencedByChangeRepositoryIdObjects gets a reference to the given []Change and assigns it to the ReferencedByChangeRepositoryIdObjects field.
func (o *Repository) SetReferencedByChangeRepositoryIdObjects(v []Change) {
	o.ReferencedByChangeRepositoryIdObjects = v
}

// GetReferencedByJobRepositoryIdObjects returns the ReferencedByJobRepositoryIdObjects field value if set, zero value otherwise.
func (o *Repository) GetReferencedByJobRepositoryIdObjects() []Job {
	if o == nil || IsNil(o.ReferencedByJobRepositoryIdObjects) {
		var ret []Job
		return ret
	}
	return o.ReferencedByJobRepositoryIdObjects
}

// GetReferencedByJobRepositoryIdObjectsOk returns a tuple with the ReferencedByJobRepositoryIdObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetReferencedByJobRepositoryIdObjectsOk() ([]Job, bool) {
	if o == nil || IsNil(o.ReferencedByJobRepositoryIdObjects) {
		return nil, false
	}
	return o.ReferencedByJobRepositoryIdObjects, true
}

// HasReferencedByJobRepositoryIdObjects returns a boolean if a field has been set.
func (o *Repository) HasReferencedByJobRepositoryIdObjects() bool {
	if o != nil && !IsNil(o.ReferencedByJobRepositoryIdObjects) {
		return true
	}

	return false
}

// SetReferencedByJobRepositoryIdObjects gets a reference to the given []Job and assigns it to the ReferencedByJobRepositoryIdObjects field.
func (o *Repository) SetReferencedByJobRepositoryIdObjects(v []Job) {
	o.ReferencedByJobRepositoryIdObjects = v
}

// GetRepositorySyncerClaimedUntil returns the RepositorySyncerClaimedUntil field value if set, zero value otherwise.
func (o *Repository) GetRepositorySyncerClaimedUntil() time.Time {
	if o == nil || IsNil(o.RepositorySyncerClaimedUntil) {
		var ret time.Time
		return ret
	}
	return *o.RepositorySyncerClaimedUntil
}

// GetRepositorySyncerClaimedUntilOk returns a tuple with the RepositorySyncerClaimedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetRepositorySyncerClaimedUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RepositorySyncerClaimedUntil) {
		return nil, false
	}
	return o.RepositorySyncerClaimedUntil, true
}

// HasRepositorySyncerClaimedUntil returns a boolean if a field has been set.
func (o *Repository) HasRepositorySyncerClaimedUntil() bool {
	if o != nil && !IsNil(o.RepositorySyncerClaimedUntil) {
		return true
	}

	return false
}

// SetRepositorySyncerClaimedUntil gets a reference to the given time.Time and assigns it to the RepositorySyncerClaimedUntil field.
func (o *Repository) SetRepositorySyncerClaimedUntil(v time.Time) {
	o.RepositorySyncerClaimedUntil = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Repository) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Repository) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Repository) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Repository) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Repository) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Repository) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Repository) SetUrl(v string) {
	o.Url = &v
}

func (o Repository) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Repository) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.HandledAt) {
		toSerialize["handled_at"] = o.HandledAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ReferencedByChangeRepositoryIdObjects) {
		toSerialize["referenced_by_change_repository_id_objects"] = o.ReferencedByChangeRepositoryIdObjects
	}
	if !IsNil(o.ReferencedByJobRepositoryIdObjects) {
		toSerialize["referenced_by_job_repository_id_objects"] = o.ReferencedByJobRepositoryIdObjects
	}
	if !IsNil(o.RepositorySyncerClaimedUntil) {
		toSerialize["repository_syncer_claimed_until"] = o.RepositorySyncerClaimedUntil
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableRepository struct {
	value *Repository
	isSet bool
}

func (v NullableRepository) Get() *Repository {
	return v.value
}

func (v *NullableRepository) Set(val *Repository) {
	v.value = val
	v.isSet = true
}

func (v NullableRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepository(val *Repository) *NullableRepository {
	return &NullableRepository{value: val, isSet: true}
}

func (v NullableRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


