/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the DependsOn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DependsOn{}

// DependsOn struct for DependsOn
type DependsOn struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Id *string `json:"id,omitempty"`
	SinkJobId *string `json:"sink_job_id,omitempty"`
	SinkJobIdObject *Job `json:"sink_job_id_object,omitempty"`
	SourceJobId *string `json:"source_job_id,omitempty"`
	SourceJobIdObject *Job `json:"source_job_id_object,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewDependsOn instantiates a new DependsOn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDependsOn() *DependsOn {
	this := DependsOn{}
	return &this
}

// NewDependsOnWithDefaults instantiates a new DependsOn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDependsOnWithDefaults() *DependsOn {
	this := DependsOn{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DependsOn) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DependsOn) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DependsOn) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *DependsOn) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *DependsOn) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *DependsOn) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DependsOn) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DependsOn) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DependsOn) SetId(v string) {
	o.Id = &v
}

// GetSinkJobId returns the SinkJobId field value if set, zero value otherwise.
func (o *DependsOn) GetSinkJobId() string {
	if o == nil || IsNil(o.SinkJobId) {
		var ret string
		return ret
	}
	return *o.SinkJobId
}

// GetSinkJobIdOk returns a tuple with the SinkJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetSinkJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.SinkJobId) {
		return nil, false
	}
	return o.SinkJobId, true
}

// HasSinkJobId returns a boolean if a field has been set.
func (o *DependsOn) HasSinkJobId() bool {
	if o != nil && !IsNil(o.SinkJobId) {
		return true
	}

	return false
}

// SetSinkJobId gets a reference to the given string and assigns it to the SinkJobId field.
func (o *DependsOn) SetSinkJobId(v string) {
	o.SinkJobId = &v
}

// GetSinkJobIdObject returns the SinkJobIdObject field value if set, zero value otherwise.
func (o *DependsOn) GetSinkJobIdObject() Job {
	if o == nil || IsNil(o.SinkJobIdObject) {
		var ret Job
		return ret
	}
	return *o.SinkJobIdObject
}

// GetSinkJobIdObjectOk returns a tuple with the SinkJobIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetSinkJobIdObjectOk() (*Job, bool) {
	if o == nil || IsNil(o.SinkJobIdObject) {
		return nil, false
	}
	return o.SinkJobIdObject, true
}

// HasSinkJobIdObject returns a boolean if a field has been set.
func (o *DependsOn) HasSinkJobIdObject() bool {
	if o != nil && !IsNil(o.SinkJobIdObject) {
		return true
	}

	return false
}

// SetSinkJobIdObject gets a reference to the given Job and assigns it to the SinkJobIdObject field.
func (o *DependsOn) SetSinkJobIdObject(v Job) {
	o.SinkJobIdObject = &v
}

// GetSourceJobId returns the SourceJobId field value if set, zero value otherwise.
func (o *DependsOn) GetSourceJobId() string {
	if o == nil || IsNil(o.SourceJobId) {
		var ret string
		return ret
	}
	return *o.SourceJobId
}

// GetSourceJobIdOk returns a tuple with the SourceJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetSourceJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceJobId) {
		return nil, false
	}
	return o.SourceJobId, true
}

// HasSourceJobId returns a boolean if a field has been set.
func (o *DependsOn) HasSourceJobId() bool {
	if o != nil && !IsNil(o.SourceJobId) {
		return true
	}

	return false
}

// SetSourceJobId gets a reference to the given string and assigns it to the SourceJobId field.
func (o *DependsOn) SetSourceJobId(v string) {
	o.SourceJobId = &v
}

// GetSourceJobIdObject returns the SourceJobIdObject field value if set, zero value otherwise.
func (o *DependsOn) GetSourceJobIdObject() Job {
	if o == nil || IsNil(o.SourceJobIdObject) {
		var ret Job
		return ret
	}
	return *o.SourceJobIdObject
}

// GetSourceJobIdObjectOk returns a tuple with the SourceJobIdObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetSourceJobIdObjectOk() (*Job, bool) {
	if o == nil || IsNil(o.SourceJobIdObject) {
		return nil, false
	}
	return o.SourceJobIdObject, true
}

// HasSourceJobIdObject returns a boolean if a field has been set.
func (o *DependsOn) HasSourceJobIdObject() bool {
	if o != nil && !IsNil(o.SourceJobIdObject) {
		return true
	}

	return false
}

// SetSourceJobIdObject gets a reference to the given Job and assigns it to the SourceJobIdObject field.
func (o *DependsOn) SetSourceJobIdObject(v Job) {
	o.SourceJobIdObject = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DependsOn) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependsOn) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DependsOn) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *DependsOn) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o DependsOn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DependsOn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SinkJobId) {
		toSerialize["sink_job_id"] = o.SinkJobId
	}
	if !IsNil(o.SinkJobIdObject) {
		toSerialize["sink_job_id_object"] = o.SinkJobIdObject
	}
	if !IsNil(o.SourceJobId) {
		toSerialize["source_job_id"] = o.SourceJobId
	}
	if !IsNil(o.SourceJobIdObject) {
		toSerialize["source_job_id_object"] = o.SourceJobIdObject
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableDependsOn struct {
	value *DependsOn
	isSet bool
}

func (v NullableDependsOn) Get() *DependsOn {
	return v.value
}

func (v *NullableDependsOn) Set(val *DependsOn) {
	v.value = val
	v.isSet = true
}

func (v NullableDependsOn) IsSet() bool {
	return v.isSet
}

func (v *NullableDependsOn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDependsOn(val *DependsOn) *NullableDependsOn {
	return &NullableDependsOn{value: val, isSet: true}
}

func (v NullableDependsOn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDependsOn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


