/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the TriggerJobExecutorClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerJobExecutorClaimRequest{}

// TriggerJobExecutorClaimRequest struct for TriggerJobExecutorClaimRequest
type TriggerJobExecutorClaimRequest struct {
	TimeoutSeconds *float64   `json:"timeout_seconds,omitempty"`
	Until          *time.Time `json:"until,omitempty"`
}

// NewTriggerJobExecutorClaimRequest instantiates a new TriggerJobExecutorClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerJobExecutorClaimRequest() *TriggerJobExecutorClaimRequest {
	this := TriggerJobExecutorClaimRequest{}
	return &this
}

// NewTriggerJobExecutorClaimRequestWithDefaults instantiates a new TriggerJobExecutorClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerJobExecutorClaimRequestWithDefaults() *TriggerJobExecutorClaimRequest {
	this := TriggerJobExecutorClaimRequest{}
	return &this
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *TriggerJobExecutorClaimRequest) GetTimeoutSeconds() float64 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret float64
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerJobExecutorClaimRequest) GetTimeoutSecondsOk() (*float64, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *TriggerJobExecutorClaimRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given float64 and assigns it to the TimeoutSeconds field.
func (o *TriggerJobExecutorClaimRequest) SetTimeoutSeconds(v float64) {
	o.TimeoutSeconds = &v
}

// GetUntil returns the Until field value if set, zero value otherwise.
func (o *TriggerJobExecutorClaimRequest) GetUntil() time.Time {
	if o == nil || IsNil(o.Until) {
		var ret time.Time
		return ret
	}
	return *o.Until
}

// GetUntilOk returns a tuple with the Until field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerJobExecutorClaimRequest) GetUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Until) {
		return nil, false
	}
	return o.Until, true
}

// HasUntil returns a boolean if a field has been set.
func (o *TriggerJobExecutorClaimRequest) HasUntil() bool {
	if o != nil && !IsNil(o.Until) {
		return true
	}

	return false
}

// SetUntil gets a reference to the given time.Time and assigns it to the Until field.
func (o *TriggerJobExecutorClaimRequest) SetUntil(v time.Time) {
	o.Until = &v
}

func (o TriggerJobExecutorClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerJobExecutorClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Until) {
		toSerialize["until"] = o.Until
	}
	return toSerialize, nil
}

type NullableTriggerJobExecutorClaimRequest struct {
	value *TriggerJobExecutorClaimRequest
	isSet bool
}

func (v NullableTriggerJobExecutorClaimRequest) Get() *TriggerJobExecutorClaimRequest {
	return v.value
}

func (v *NullableTriggerJobExecutorClaimRequest) Set(val *TriggerJobExecutorClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerJobExecutorClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerJobExecutorClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerJobExecutorClaimRequest(val *TriggerJobExecutorClaimRequest) *NullableTriggerJobExecutorClaimRequest {
	return &NullableTriggerJobExecutorClaimRequest{value: val, isSet: true}
}

func (v NullableTriggerJobExecutorClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerJobExecutorClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
